import "./globals.css"
import { Inter } from "next/font/google"

import Navbar from "./components/Navbar"

import { ThemeProvider } from "../components/ui/theme-provider.jsx"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Blogmish | Blog App",
  description: "Generated by create nextjs and sanity!",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`container mx-auto ${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}